### ISSUE TITLE
Adding Header to request from script fails

### ISSUE THREAD

**Issue by justin1291** [hao1300/modheader#4]
#### Application Versions: 
Chrome 76
ModHeader 2.3.6

#### Issue: 
Unable to add a request header to a request made by web application.
Directly accessing API applies header, but web app request of api does not have header applied.

**Comment by EmperorEarth** [comment]
I think my issue is related to yours

The latest version doesn't seem to modify the headers for child routes anymore

**Comment by hao1300** [comment]
Should be fixed now in https://github.com/hao1300/modheader/commit/0470733eefc48033cc8ed561d5340f5a724c4f48

**Comment by justin1291** [comment]
Upgraded to ModHeader 2.3.7 and I am still facing the same issue.

Example:

Go to https://jsonplaceholder.typicode.com/ 

click try it.

Expect: 

Header 'test' to be added, but is missing from request. See below:

```
:authority: jsonplaceholder.typicode.com
:method: GET
:path: /todos/1
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
cookie: __cfduid=de566ba2ca51222db7c89df21625302a81564947597
dnt: 1
pragma: no-cache
referer: https://jsonplaceholder.typicode.com/
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
```

As explained in original issue. Accessing api directly works. See below:

```
:authority: jsonplaceholder.typicode.com
:method: GET
:path: /todos/1
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
cookie: __cfduid=de566ba2ca51222db7c89df21625302a81564947597
dnt: 1
pragma: no-cache
sec-fetch-mode: navigate
sec-fetch-site: none
test: header
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
```

**Comment by hao1300** [comment]
Thanks for the repro steps. I have added an option in Profile Settings to always modify request in case of CORS. Note that with Chrome 76+, Chrome would issue additional OPTIONS http request if the modifications causes the request to not be a [simple request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests) any more, which can cause some resources to not load properly, so be careful when using it.
